version: "3"

services:
  rabbitmq_server:
    image: rabbitmq:3-management
    platform: linux/arm64/v8
    container_name: rabbitmq
    hostname: rabbithost
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./server/celery_backend/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./server/celery_backend/definitions.json:/etc/rabbitmq/definitions.json:ro
    env_file:
      - .env
    networks:
      - dhruva-network

  celery-metering:
    container_name: celery-metering
    image: server
    platform: linux/arm64/v8
    working_dir: /src
    depends_on:
      rabbitmq_server:
        condition: service_started
      timescaledb:
        condition: service_healthy
    volumes:
      - ./server:/src
    environment:
      - TIMESCALE_USER=${TIMESCALE_USER}
      - TIMESCALE_PASSWORD=${TIMESCALE_PASSWORD}
      - TIMESCALE_DATABASE_NAME=${TIMESCALE_DATABASE_NAME}
      - TIMESCALE_HOST=${TIMESCALE_HOST}
      - TIMESCALE_PORT=${TIMESCALE_PORT}
    env_file:
      - .env
    # Original command with heartbeat queue:
    # command: sh -c "python3 -m celery -A celery_backend.celery_app worker -Q data-log,heartbeat,upload-feedback-dump,send-usage-email"
    command: sh -c "python3 -m celery -A celery_backend.celery_app worker -Q data-log,upload-feedback-dump,send-usage-email"
    networks:
      - dhruva-network

  celery-monitoring:
    container_name: celery-monitoring
    image: server
    platform: linux/arm64/v8
    build:
      context: ./server
    working_dir: /src
    depends_on:
      rabbitmq_server:
        condition: service_started
    volumes:
      - ./server:/src
    env_file:
      - .env
    command: sh -c "python3 -m celery -A celery_backend.celery_app worker -Q metrics-log"
    networks:
      - dhruva-network

  celery_beat:
    container_name: celery_beat
    image: server
    platform: linux/arm64/v8
    working_dir: /src
    depends_on:
      rabbitmq_server:
        condition: service_started
      celery-metering:
        condition: service_started
    volumes:
      - ./server:/src
    env_file:
      - .env
    command: sh -c "python3 -m celery -A celery_backend.celery_app beat --loglevel DEBUG"
    networks:
      - dhruva-network

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg15
    platform: linux/arm64/v8
    hostname: timescaledb
    ports:
      - "5432:5432"
    volumes:
      - timescaledb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE_NAME}
    env_file:
      - .env
    networks:
      - dhruva-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Use Flower later for monitoring
  # celery-flower:
  #   container_name: celery-flower
  #   image: server_image
  #   working_dir: /src
  #   environment:
  #     - AMQP_USERNAME=user
  #     - AMQP_PASSWORD=user
  #     - AMQP_ADMIN_USERNAME=admin
  #     - AMQP_ADMIN_PASSWORD=admin
  #     - AMQP_HOST=dhruva_host
  #     - AMQP_PORT=5672
  #     - AMQP_ADMIN_HOST=dhruva_host
  #     - AMQP_ADMIN_PORT=15672
  #     - FLOWER_BASIC_AUTH=user:user
  #   volumes:
  #     - ./server:/src
  #   ports:
  #     - "5555:5555"
  #   command: sh -c "python3 -m celery -A celery_backend.celery_app flower --port=5555 --basic_auth=admin:admin --broker_api=http://admin:admin@rabbithost:15672/api/ --address=0.0.0.0"

volumes:
  timescaledb: {}

networks:
  dhruva-network:
    name: dhruva-network
    external: true
