version: "3"

services:
  app_db:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: app_db
    ports:
      - "27017:27017"
    volumes:
      - app_db:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dhruvaadmin
      - MONGO_INITDB_ROOT_PASSWORD=dhruva123
      - MONGO_INITDB_DATABASE=admin
    env_file:
      - .env
    networks:
      - dhruva-network

  log_db:
    image: mongo:latest
    platform: linux/arm64/v8
    container_name: log_db
    ports:
      - "27018:27017"
    volumes:
      - log_db:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dhruvalog
      - MONGO_INITDB_ROOT_PASSWORD=dhruva123
      - MONGO_INITDB_DATABASE=admin
    env_file:
      - .env
    networks:
      - dhruva-network
  
  redis:
    image: redis:latest
    platform: linux/arm64/v8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped
    networks:
      - dhruva-network

  mongo_admin:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=app_db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dhruvaadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dhruva123
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - app_db
    networks:
      - dhruva-network
    
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    platform: linux/arm64/v8
    container_name: timescaledb
    ports:
      - "5432:5432"
    volumes:
      - timescaledb:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$TIMESCALEDB_USERNAME
      - POSTGRES_PASSWORD=$TIMESCALEDB_PASSWORD
      - POSTGRES_DB=$TIMESCALEDB_DATABASE
    env_file:
      - .env
    networks:
      - dhruva-network

volumes:
  app_db: {}
  log_db: {}
  redis: {}
  mongo_admin: {}
  timescaledb: {}

networks:
  dhruva-network:
    name: dhruva-network
    external: true