version: "3"

services:
  rabbitmq_server:
    image: rabbitmq:3-management
    container_name: rabbitmq
    platform: linux/arm64/v8
    hostname: rabbithost
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./server/celery_backend/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./server/celery_backend/definitions.json:/etc/rabbitmq/definitions.json:ro
    env_file:
      - .env
    networks:
      - dhruva-network

  celery-metering:
    container_name: celery-metering
    platform: linux/arm64/v8
    build:
      context: ./server
    working_dir: /src
    depends_on:
      rabbitmq_server:
        condition: service_started
      timescaledb:
        condition: service_healthy
    volumes:
      - ./server:/src
    env_file:
      - .env
    command: sh -c "python3 -m celery -A celery_backend.celery_app worker -Q data-log,heartbeat,upload-feedback-dump,send-usage-email"
    networks:
      - dhruva-network

  celery-monitoring:
    container_name: celery-monitoring
    platform: linux/arm64/v8
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /src
    depends_on:
      rabbitmq_server:
        condition: service_started
      timescaledb:
        condition: service_healthy
    volumes:
      - ./server:/src
    env_file:
      - .env
    command: sh -c "python3 -m celery -A celery_backend.celery_app worker -Q metrics-log"
    networks:
      - dhruva-network

  celery_beat:
    container_name: celery_beat
    platform: linux/arm64/v8
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /src
    depends_on:
      rabbitmq_server:
        condition: service_started
      celery-metering:
        condition: service_started
      timescaledb:
        condition: service_healthy
    volumes:
      - ./server:/src
    env_file:
      - .env
    command: sh -c "python3 -m celery -A celery_backend.celery_app beat --loglevel DEBUG"
    networks:
      - dhruva-network

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: dhruva-platform-timescaledb
    platform: linux/arm64/v8
    restart: always
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE_NAME}
    ports:
      - "${TIMESCALE_PORT}:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dhruva-network

volumes:
  timescaledb_data:

networks:
  dhruva-network:
    name: dhruva-network
    external: true
