version: "3"

services:
  app_db:
    image: mongo:6.0
    container_name: dhruva-platform-app-db
    platform: linux/arm64/v8
    ports:
      - "27017:27017"
    volumes:
      - app_db:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dhruvaadmin
      - MONGO_INITDB_ROOT_PASSWORD=dhruva123
    networks:
      - dhruva-network

  log_db:
    image: mongo:6.0
    container_name: dhruva-platform-log-db
    ports:
      - "27018:27017"
    volumes:
      - log_db:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dhruvalog
      - MONGO_INITDB_ROOT_PASSWORD=dhruva123
    networks:
      - dhruva-network
  
  redis:
    image: redis:7.0.11
    container_name: dhruva-platform-redis
    platform: linux/arm64/v8
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --requirepass dhruva123 --save 20 1 --loglevel warning
    restart: unless-stopped
    networks:
      - dhruva-network

  mongo_express:
    image: mongo-express:latest
    container_name: dhruva-platform-mongo-express
    platform: linux/arm64/v8
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dhruvaadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=dhruva123
      - ME_CONFIG_MONGODB_URL=mongodb://dhruvaadmin:dhruva123@dhruva-platform-app-db:27017/
    depends_on:
      - app_db
    networks:
      - dhruva-network

volumes:
  app_db: {}
  log_db: {}
  redis: {}

networks:
  dhruva-network:
    name: dhruva-network