#made changes to get this file working for the first time. 

version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dhruva-platform-server
    restart: always
    command: python3 main.py
    ports:
      - "8000:8000"
    environment:
      - MONGO_APP_DB_USERNAME=${MONGO_APP_DB_USERNAME}
      - MONGO_APP_DB_PASSWORD=${MONGO_APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
      - MONGO_LOG_DB_USERNAME=${MONGO_LOG_DB_USERNAME}
      - MONGO_LOG_DB_PASSWORD=${MONGO_LOG_DB_PASSWORD}
      - LOG_DB_NAME=${LOG_DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SECURE=false
      - TIMESCALE_USER=${TIMESCALE_USER}
      - TIMESCALE_PASSWORD=${TIMESCALE_PASSWORD}
      - TIMESCALE_DATABASE_NAME=${TIMESCALE_DATABASE_NAME}
      - TIMESCALE_HOST=${TIMESCALE_HOST}
      - TIMESCALE_PORT=${TIMESCALE_PORT}
    depends_on:
      app_db:
        condition: service_healthy
      log_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    networks:
      - dhruva_network

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dhruva-platform-worker
    restart: always
    command: celery -A celery_backend.celery_app worker --loglevel=info
    environment:
      - MONGO_APP_DB_USERNAME=${MONGO_APP_DB_USERNAME}
      - MONGO_APP_DB_PASSWORD=${MONGO_APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
      - MONGO_LOG_DB_USERNAME=${MONGO_LOG_DB_USERNAME}
      - MONGO_LOG_DB_PASSWORD=${MONGO_LOG_DB_PASSWORD}
      - LOG_DB_NAME=${LOG_DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SECURE=false
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - APP_DB_CONNECTION_STRING=mongodb://${MONGO_APP_DB_USERNAME}:${MONGO_APP_DB_PASSWORD}@app_db:27017/${APP_DB_NAME}
      - LOG_DB_CONNECTION_STRING=mongodb://${MONGO_LOG_DB_USERNAME}:${MONGO_LOG_DB_PASSWORD}@log_db:27017/${LOG_DB_NAME}
      - TIMESCALE_USER=${TIMESCALE_USER}
      - TIMESCALE_PASSWORD=${TIMESCALE_PASSWORD}
      - TIMESCALE_DATABASE_NAME=${TIMESCALE_DATABASE_NAME}
      - TIMESCALE_HOST=${TIMESCALE_HOST}
      - TIMESCALE_PORT=${TIMESCALE_PORT}
    depends_on:
      app_db:
        condition: service_healthy
      log_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    networks:
      - dhruva_network

  app_db:
    image: mongo:6.0
    container_name: dhruva-platform-app-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_APP_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_APP_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${APP_DB_NAME}
    volumes:
      - app_db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dhruva_network

  log_db:
    image: mongo:6.0
    container_name: dhruva-platform-log-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOG_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_LOG_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${LOG_DB_NAME}
    volumes:
      - log_db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dhruva_network

  redis:
    image: redis:7.0.11
    container_name: dhruva-platform-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - dhruva_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: dhruva-platform-timescaledb
    restart: always
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DATABASE_NAME}
    ports:
      - "${TIMESCALE_PORT}:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TIMESCALE_USER} -d ${TIMESCALE_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dhruva_network

volumes:
  app_db_data:
  log_db_data:
  redis_data:
  timescaledb_data:

networks:
  dhruva_network:
    name: dhruva-network
    external: true
