#made changes to get this file working for the first time. 

services:
  server:
    image: dhruva-platform-server:latest-pg15
    container_name: dhruva-platform-server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGODB_URI=mongodb://${MONGO_APP_DB_USERNAME}:${MONGO_APP_DB_PASSWORD}@app_db:27017/admin?authSource=admin
      - APP_DB_CONNECTION_STRING=mongodb://${MONGO_APP_DB_USERNAME}:${MONGO_APP_DB_PASSWORD}@app_db:27017/admin?authSource=admin
      - RABBITMQ_HOST=rabbitmq_server
      - RABBITMQ_PORT=5672
      - TIMESCALE_HOST=timescaledb
      - TIMESCALE_PORT=5432
      - TIMESCALE_USER=${TIMESCALE_USER}
      - TIMESCALE_PASSWORD=${TIMESCALE_PASSWORD}
      - TIMESCALE_DATABASE_NAME=${TIMESCALE_DATABASE_NAME}
    depends_on:
      redis:
        condition: service_healthy
      app_db:
        condition: service_healthy
      rabbitmq_server:
        condition: service_started
      timescaledb:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - dhruva-network

  worker:
    image: dhruva-platform-worker:latest
    container_name: dhruva-platform-worker
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    command: >
      celery -A celery_backend.celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      app_db:
        condition: service_healthy
      rabbitmq_server:
        condition: service_started
      timescaledb:
        condition: service_healthy
    networks:
      - dhruva-network

  flower:
    build:
      context: .
      dockerfile: docker/flower/Dockerfile
    container_name: dhruva-platform-flower
    ports:
      - "5555:5555"
    depends_on:
      rabbitmq_server:
        condition: service_healthy
    networks:
      - dhruva-network


volumes:
  timescaledb_data:
  app_db_data:
  log_db_data:
  redis_data:

networks:
  dhruva-network:
    name: dhruva-network
