apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://dhruva-platform-prometheus:9090
    basicAuth: false
    isDefault: true
    editable: false
    uid: kdjfS_R7c
